### ISSUE TITLE
CHANNEL CREATION FAILED: Error: Error: Failed to create the channel. 

### ISSUE THREAD

**Issue by servntire** [HyperledgerHandsOn/trade-finance-logistics#18] opened 2018-07-13 20:09 UTC
Getting error when running **node createTradeApp.js**
- Docker containers are up and running.
- Dependencies are correct.

<img width="1260" alt="screen shot 2018-07-14 at 12 41 57 am" src="https://user-images.githubusercontent.com/37290744/42711740-a3eee6f0-8706-11e8-9100-7afdf95b7848.png">

**Comment by VRamakrishna** [comment] 2018-07-13 20:55
Clearly the `client.createChannel(...)` failed, but it's hard to say what the problem was without more info. Can you paste the results of `docker ps -a`, and also attach the network log file (the default should be `<root-folder>/network/logs/network.log`)?

**Comment by servntire** [comment] 2018-07-13 21:09
I'm executing the project as follows.
DIR **network**
./trade.sh up
`CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                                                       NAMES
090492aac76a        hyperledger/fabric-ca:latest        "sh -c 'fabric-ca-se…"   2 hours ago         Up About a minute   0.0.0.0:7054->7054/tcp                                                      ca_peerExporterOrg
d05185b04ef4        hyperledger/fabric-ca:latest        "sh -c 'fabric-ca-se…"   2 hours ago         Up About a minute   0.0.0.0:10054->7054/tcp                                                     ca_peerRegulatorOrg
e429e94a4896        hyperledger/fabric-ca:latest        "sh -c 'fabric-ca-se…"   2 hours ago         Up About a minute   0.0.0.0:9054->7054/tcp                                                      ca_peerCarrierOrg
d831241c9d4b        hyperledger/fabric-ca:latest        "sh -c 'fabric-ca-se…"   2 hours ago         Up About a minute   0.0.0.0:8054->7054/tcp                                                      ca_peerImporterOrg
2ddcaca2ab34        hyperledger/fabric-peer:latest      "peer node start"        2 hours ago         Up About a minute   0.0.0.0:10055->6060/tcp, 0.0.0.0:10051->7051/tcp, 0.0.0.0:10053->7053/tcp   peer0.regulatororg.trade.com
7caba45fa694        hyperledger/fabric-peer:latest      "peer node start"        2 hours ago         Up About a minute   0.0.0.0:8055->6060/tcp, 0.0.0.0:8051->7051/tcp, 0.0.0.0:8053->7053/tcp      peer0.importerorg.trade.com
7fdfdeb1d0e2        hyperledger/fabric-peer:latest      "peer node start"        2 hours ago         Up About a minute   0.0.0.0:7051->7051/tcp, 0.0.0.0:7053->7053/tcp, 0.0.0.0:7055->6060/tcp      peer0.exporterorg.trade.com
b8bf8698862e        hyperledger/fabric-orderer:latest   "orderer"                2 hours ago         Up About a minute   0.0.0.0:7050->7050/tcp                                                      orderer.trade.com
44638dff878a        hyperledger/fabric-peer:latest      "peer node start"        2 hours ago         Up About a minute   0.0.0.0:9055->6060/tcp, 0.0.0.0:9051->7051/tcp, 0.0.0.0:9053->7053/tcp      peer0.carrierorg.trade.com`

DIR **middleware**
node createTradeApp.js

<img width="1254" alt="screen shot 2018-07-14 at 2 38 28 am" src="https://user-images.githubusercontent.com/37290744/42713985-05ae06f2-870f-11e8-906f-fc0a31961bea.png">

<img width="1280" alt="screen shot 2018-07-14 at 2 38 05 am" src="https://user-images.githubusercontent.com/37290744/42713958-fab9689a-870e-11e8-92b9-eac074edb58b.png">

**NetworkLog**
[network.log](https://github.com/HyperledgerHandsOn/trade-finance-logistics/files/2194182/network.log)

**Comment by servntire** [comment] 2018-07-14 08:31
I  tried it again. The ca is getting exited. **Earlier I solved it by replacing `ORG`_CA_PRIVATE_KEY manually into the docker-compose-e2e.yaml file**

<img width="1279" alt="screen shot 2018-07-14 at 1 57 47 pm" src="https://user-images.githubusercontent.com/37290744/42722674-f190d1b8-876d-11e8-83ae-154043db6fbb.png">

Attaching the network log.
[network.log](https://github.com/HyperledgerHandsOn/trade-finance-logistics/files/2194789/network.log)

Looks like something is missing.

**Comment by VRamakrishna** [comment] 2018-07-14 08:37
Did you run `./trade.sh generate -c tradechannel`? That command is supposed to replace the variable with the generated key file location. Did you observe any errors when you ran the command?

**Comment by shalini-kad** [comment] 2018-07-14 09:04
It was not replacing the place holders. _OS X requires the extension to be explicitly specified. The So I added an empty string. Now it's properly generating the e2e-compose file.
<img width="547" alt="screen shot 2018-07-14 at 2 25 22 pm" src="https://user-images.githubusercontent.com/34833306/42722958-9c0552f0-8772-11e8-8910-70a323b2bb6b.png">
<img width="667" alt="screen shot 2018-07-14 at 2 28 06 pm" src="https://user-images.githubusercontent.com/34833306/42722963-a5d7aeb8-8772-11e8-82c3-af9d6300da5d.png">

But still the issue is existing.
<img width="1279" alt="screen shot 2018-07-14 at 2 29 55 pm" src="https://user-images.githubusercontent.com/34833306/42722969-b3494840-8772-11e8-89c8-b66e759b387f.png">

From network log, I assume it's related to certificate validation.  _Principal deserialization failure (the supplied identity is not valid: x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" or policy._

Networklog
[network.log](https://github.com/HyperledgerHandsOn/trade-finance-logistics/files/2194803/network.log)

**Comment by servntire** [comment] 2018-07-14 09:45
**Resolved the issue by clearing docker volumes and removing docker images.**

<img width="1280" alt="screen shot 2018-07-14 at 3 08 44 pm" src="https://user-images.githubusercontent.com/37290744/42723248-0eb63d64-8778-11e8-9a8a-c37e02aa3e90.png">

Error: **status: 500, message:  is not a valid endorsement system chaincode**

Network Log
[network.log](https://github.com/HyperledgerHandsOn/trade-finance-logistics/files/2194855/network.log)

**Comment by VRamakrishna** [comment] 2018-07-14 09:51
OK, I understand now. I tested the setup and application on Linux (Ubuntu), and in an Ubuntu Box on Windows using Vagrant.

@ldesrosi Do you have any tips to share for setup and runs on a Mac?

**Comment by servntire** [comment] 2018-07-14 09:59
@VRamakrishna Can you please check my previous comment also.

**Comment by VRamakrishna** [comment] 2018-07-28 07:53
Still seeing these issues? If not, can we close this out?

**Comment by VRamakrishna** [comment] 2018-08-14 06:51
Closing due to inactivity.

**Closed by VRamakrishna** 2018-08-14 06:51 UTC

**Comment by tomorenge** [comment] 2020-05-31 07:50
am getting the same error while running node createTradeApp.js
